name: BetterChat-RE
version: '1.9'
main: com.LiuLiEYEs.BetterChat.Main
api-version: '1.21'
authors: [ LiuLI_EYEs ]
folia-supported: true
commands:
  LiuLIBetterChat:
    aliases:
      - lbc
      - bc
